version: '3.3'
services: 
  gitlab:
    image: 'gitlab/gitlab-ce:11.11.8-ce.0'
    volumes: 
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports: 
      - 1080:80
      - 1022:22
    restart: unless-stopped

  jenkins:
    image: 'jenkinsci/blueocean'
    user: root
    volumes: 
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 2080:8080
    restart: unless-stopped

  sonarqube:
    image: 'sonarqube:7.9.1-community'
    volumes:
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/temp:/opt/sonarqube/temp
    ports:
      - 3080:9000
    restart: unless-stopped

networks:
  default:
    external:
      name: cicd
