version: '3.3'
services: 
  gitlab:
    image: 'gitlab/gitlab-ce'
    volumes: 
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports: 
      - 1080:80
      - 1022:22
    restart: unless-stopped

  jenkins:
    image: 'jenkins/jenkins:lts'
    volumes: 
      - ./jenkins:/var/jenkins_home
    ports: 
      - 2080:8080
    restart: unless-stopped